[package]
name = "pacpreview"
version = "0.1.0"
authors = ["Stephen E. Baker <baker.stephen.e@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"alpm"="1.1"
